exclude:  ['README.md', 'Makefile', 'assets/less', 'assets/vendor/bootstrap', 'indexTemplate.md']
timezone: America/Los_Angeles
markdown: kramdown
kramdown:
  toc_levels: "1,2,3,4,5"
plugins:
  - jekyll-sitemap
  - jemoji
